# Generated by Django 5.0.1 on 2024-01-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernet',
            name='first_login',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usernet',
            name='middle_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usernet',
            name='phone_number',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
