# Generated by Django 5.0.1 on 2024-01-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_usernet_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernet',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
