# Generated by Django 5.0.1 on 2024-01-18 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_technology_usernet_technology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernet',
            name='technology',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
