# Generated by Django 5.0.1 on 2024-01-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_message_options_rename_author_message_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(default=True, max_length=300),
        ),
    ]
